name: Daily Site Update

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC daily
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install the package in editable mode with all dependencies
        python -m pip install -e . || exit 1
        
        # Verify installations
        echo "Verifying package installations..."
        python -c "import feedparser, flask, flask_frozen, yaml, email_validator, flask_sqlalchemy, psycopg2" || exit 1
        
        # Verify package structure
        echo "Verifying package structure..."
        python -c "from app import app" || exit 1
        
    - name: Convert feeds
      run: |
        echo "Converting feeds from YAML to JSON..."
        python -m app.convert_feeds
        if [ ! -f feeds.json ]; then
          echo "Error: feeds.json was not created"
          exit 1
        fi
        
    - name: Build static site
      run: |
        echo "Building static site..."
        python -m app.build
        
        # Verify build output
        if [ ! -d "build" ]; then
          echo "Error: build directory was not created"
          exit 1
        fi
        if [ ! -f "build/index.html" ]; then
          echo "Error: index.html was not generated"
          exit 1
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        force_orphan: true
