name: Daily Site Update

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC daily
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install packages with exact versions from pyproject.toml
        python -m pip install \
          feedparser==6.0.11 \
          flask==3.1.0 \
          frozen-flask==1.0.2 \
          pyyaml==6.0.2 \
          email-validator==2.2.0 \
          flask-sqlalchemy==3.1.1 \
          psycopg2-binary==2.9.10 \
          || exit 1  # Exit if installation fails
        
        # Verify installations
        echo "Verifying package installations..."
        python -c "import feedparser, flask, flask_frozen, yaml, email_validator, flask_sqlalchemy, psycopg2" || exit 1
        
    - name: Convert feeds
      run: |
        echo "Converting feeds from YAML to JSON..."
        python convert_feeds.py
        if [ ! -f feeds.json ]; then
          echo "Error: feeds.json was not created"
          exit 1
        fi
        
    - name: Build static site
      run: |
        echo "Building static site..."
        python build.py
        
        # Verify build output
        if [ ! -d "build" ]; then
          echo "Error: build directory was not created"
          exit 1
        fi
        if [ ! -f "build/index.html" ]; then
          echo "Error: index.html was not generated"
          exit 1
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        force_orphan: true
